spring:
  datasource:
    url: jdbc:postgresql://localhost/persons
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10